CP4BA_INST_PFS_NAME=pfs-demo
CP4BA_INST_PFS_NAMESPACE=cp4ba-wfps-baw-pfs-demo
CP4BA_INST_PFS_STORAGE_CLASS=managed-nfs-storage
CP4BA_INST_PFS_APP_VER=25.0.1
CP4BA_INST_PFS_ADMINUSER="cpadmin"

CP4BA_INST_PFS_REPLICAS=2
CP4BA_INST_PFS_RES_REQS_CPU="1000m"
CP4BA_INST_PFS_RES_REQS_MEMORY="1024Mi"
CP4BA_INST_PFS_RES_LIMITS_REQS_CPU="2000m"
CP4BA_INST_PFS_RES_LIMITS_REQS_MEMORY="4Gi"
